
import { useState } from "react";
import "../styles/assessment.css";

import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

function Assessment() {
  const [step, setStep] = useState(1);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState("");

  const [formData, setFormData] = useState({
    name: "",
    age: "",
    location: "",
    qualification: "",
    stream: "",
    marks: "",
    passingYear: "",

    // Step 3
    goal: "",

    // Step 4
    interests: [],
    skills: "",
    budget: "",
    careerGoal: "",
  });

  // ================================
  // HANDLE INPUT CHANGE
  // ================================

  const handleChange = (e) => {
    const { name, value } = e.target;

    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  // ================================
  // SELECT INTEREST
  // ================================

  const handleInterest = (interest) => {
    setFormData((prev) => {
      if (prev.interests.includes(interest)) {
        return {
          ...prev,
          interests: prev.interests.filter(
            (item) => item !== interest
          ),
        };
      }

      return {
        ...prev,
        interests: [...prev.interests, interest],
      };
    });
  };

  // ================================
  // SELECT MAIN GOAL
  // ================================

  const handleGoal = (goal) => {
    setFormData((prev) => ({
      ...prev,
      goal,
      interests: [],
      skills: "",
      budget: "",
      careerGoal: "",
    }));

    setError("");
  };

  // ================================
  // NEXT STEP
  // ================================

  const nextStep = () => {
    setError("");

    // Step 1 validation
    if (step === 1) {
      if (
        !formData.name.trim() ||
        !formData.age ||
        !formData.location.trim()
      ) {
        setError("Please fill all basic details.");
        return;
      }
    }

    // Step 2 validation
    if (step === 2) {
      if (
        !formData.qualification ||
        !formData.stream ||
        !formData.marks.trim() ||
        !formData.passingYear
      ) {
        setError("Please complete your education details.");
        return;
      }
    }

    // Step 3 validation
    if (step === 3) {
      if (!formData.goal) {
        setError("Please select what you want to do next.");
        return;
      }
    }

    if (step < 4) {
      setStep((prev) => prev + 1);
    }
  };

  // ================================
  // PREVIOUS STEP
  // ================================

  const previousStep = () => {
    setError("");

    if (step > 1) {
      setStep((prev) => prev - 1);
    }
  };

  // ================================
  // FINAL SUBMIT
  // ================================

  const handleSubmit = async () => {
    setIsSubmitting(true);
    setError("");

    localStorage.removeItem("careerRecommendations");

    try {
      const response = await fetch(
        "http://localhost:5000/api/assessment",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(formData),
        }
      );

      const data = await response.json();

      console.log("Backend response:", data);

      if (!response.ok) {
        throw new Error(
          data.message || "Assessment submission failed"
        );
      }

      if (!Array.isArray(data.recommendations)) {
        throw new Error(
          "Career recommendations were not generated by backend."
        );
      }

      localStorage.setItem(
        "assessmentData",
        JSON.stringify(formData)
      );

      localStorage.setItem(
        "careerRecommendations",
        JSON.stringify(data.recommendations)
      );

      window.location.href = "/results";
    } catch (error) {
      console.error("Assessment submit error:", error);

      setError(
        error.message ||
          "Unable to connect to server. Please make sure the backend is running."
      );
    } finally {
      setIsSubmitting(false);
    }
  };

  // ================================
  // STEP 4 CONTENT
  // ================================

  const renderStepFour = () => {
    // ========================================
    // HIGHER STUDIES
    // ========================================

    if (formData.goal === "Higher Studies") {
      return (
        <div>
          <h2>Higher Studies</h2>

          <p className="form-description">
            Tell us what you would like to study next.
          </p>

          <div className="form-group">
            <label>Which field interests you?</label>

            <div className="options">
              {[
                "Technology",
                "Medical",
                "Business",
                "Finance",
                "Design",
                "Science",
                "Arts",
                "Law",
              ].map((interest) => (
                <button
                  type="button"
                  key={interest}
                  className={
                    formData.interests.includes(interest)
                      ? "selected"
                      : ""
                  }
                  onClick={() => handleInterest(interest)}
                >
                  {interest}
                </button>
              ))}
            </div>
          </div>

          <div className="form-group">
            <label>What do you want to pursue?</label>

            <select
              name="skills"
              value={formData.skills}
              onChange={handleChange}
            >
              <option value="">
                Select study level
              </option>

              <option value="Diploma">
                Diploma
              </option>

              <option value="Bachelor Degree">
                Bachelor's Degree
              </option>

              <option value="Master Degree">
                Master's Degree
              </option>

              <option value="Professional Course">
                Professional Course
              </option>

              <option value="PhD">
                PhD / Doctorate
              </option>
            </select>
          </div>

          <div className="form-group">
            <label>Education Budget</label>

            <select
              name="budget"
              value={formData.budget}
              onChange={handleChange}
            >
              <option value="">
                Select your budget
              </option>

              <option value="Below ₹50,000">
                Below ₹50,000
              </option>

              <option value="₹50,000 - ₹1 Lakh">
                ₹50,000 - ₹1 Lakh
              </option>

              <option value="₹1 - ₹2 Lakh">
                ₹1 - ₹2 Lakh
              </option>

              <option value="Above ₹2 Lakh">
                Above ₹2 Lakh
              </option>
            </select>
          </div>
        </div>
      );
    }

    // ========================================
    // JOB
    // ========================================

    if (formData.goal === "Get a Job") {
      return (
        <div>
          <h2>Career & Job</h2>

          <p className="form-description">
            Tell us what kind of career you are looking for.
          </p>

          <div className="form-group">
            <label>Which field interests you?</label>

            <div className="options">
              {[
                "Technology",
                "Medical",
                "Business",
                "Finance",
                "Design",
                "Government",
                "Teaching",
                "Research",
              ].map((interest) => (
                <button
                  type="button"
                  key={interest}
                  className={
                    formData.interests.includes(interest)
                      ? "selected"
                      : ""
                  }
                  onClick={() => handleInterest(interest)}
                >
                  {interest}
                </button>
              ))}
            </div>
          </div>

          <div className="form-group">
            <label>Your current skills</label>

            <input
              type="text"
              name="skills"
              value={formData.skills}
              onChange={handleChange}
              placeholder="Example: HTML, Excel, Communication..."
            />
          </div>

          <div className="form-group">
            <label>Preferred job type</label>

            <div className="options">
              {[
                "Private Job",
                "Government Job",
                "Remote Job",
                "Freelance",
              ].map((type) => (
                <button
                  type="button"
                  key={type}
                  className={
                    formData.careerGoal === type
                      ? "selected"
                      : ""
                  }
                  onClick={() =>
                    setFormData((prev) => ({
                      ...prev,
                      careerGoal: type,
                    }))
                  }
                >
                  {type}
                </button>
              ))}
            </div>
          </div>
        </div>
      );
    }

    // ========================================
    // LEARN SKILLS
    // ========================================

    if (formData.goal === "Learn Skills") {
      return (
        <div>
          <h2>Learn New Skills</h2>

          <p className="form-description">
            Tell us what you would like to learn.
          </p>

          <div className="form-group">
            <label>Which skill interests you?</label>

            <div className="options">
              {[
                "Programming",
                "AI & Machine Learning",
                "Data Science",
                "Digital Marketing",
                "Graphic Design",
                "Finance",
                "Communication",
              ].map((skill) => (
                <button
                  type="button"
                  key={skill}
                  className={
                    formData.interests.includes(skill)
                      ? "selected"
                      : ""
                  }
                  onClick={() => handleInterest(skill)}
                >
                  {skill}
                </button>
              ))}
            </div>
          </div>

          <div className="form-group">
            <label>Your current level</label>

            <div className="options">
              {[
                "Beginner",
                "Intermediate",
                "Advanced",
              ].map((level) => (
                <button
                  type="button"
                  key={level}
                  className={
                    formData.skills === level
                      ? "selected"
                      : ""
                  }
                  onClick={() =>
                    setFormData((prev) => ({
                      ...prev,
                      skills: level,
                    }))
                  }
                >
                  {level}
                </button>
              ))}
            </div>
          </div>

          <div className="form-group">
            <label>Why do you want to learn?</label>

            <div className="options">
              {[
                "For a Job",
                "For College",
                "For Freelancing",
                "Personal Interest",
              ].map((purpose) => (
                <button
                  type="button"
                  key={purpose}
                  className={
                    formData.careerGoal === purpose
                      ? "selected"
                      : ""
                  }
                  onClick={() =>
                    setFormData((prev) => ({
                      ...prev,
                      careerGoal: purpose,
                    }))
                  }
                >
                  {purpose}
                </button>
              ))}
            </div>
          </div>
        </div>
      );
    }

    // ========================================
    // BUSINESS
    // ========================================

    if (formData.goal === "Start a Business") {
      return (
        <div>
          <h2>Business Goals</h2>

          <p className="form-description">
            Tell us a little about your business plans.
          </p>

          <div className="form-group">
            <label>Which area interests you?</label>

            <div className="options">
              {[
                "Technology",
                "E-Commerce",
                "Finance",
                "Education",
                "Food",
                "Design",
                "Other",
              ].map((interest) => (
                <button
                  type="button"
                  key={interest}
                  className={
                    formData.interests.includes(interest)
                      ? "selected"
                      : ""
                  }
                  onClick={() => handleInterest(interest)}
                >
                  {interest}
                </button>
              ))}
            </div>
          </div>

          <div className="form-group">
            <label>Approximate budget</label>

            <select
              name="budget"
              value={formData.budget}
              onChange={handleChange}
            >
              <option value="">
                Select budget
              </option>

              <option value="Below ₹50,000">
                Below ₹50,000
              </option>

              <option value="₹50,000 - ₹1 Lakh">
                ₹50,000 - ₹1 Lakh
              </option>

              <option value="₹1 - ₹5 Lakh">
                ₹1 - ₹5 Lakh
              </option>

              <option value="Above ₹5 Lakh">
                Above ₹5 Lakh
              </option>
            </select>
          </div>

          <div className="form-group">
            <label>Do you have business experience?</label>

            <div className="options">
              {["Yes", "No"].map((answer) => (
                <button
                  type="button"
                  key={answer}
                  className={
                    formData.skills === answer
                      ? "selected"
                      : ""
                  }
                  onClick={() =>
                    setFormData((prev) => ({
                      ...prev,
                      skills: answer,
                    }))
                  }
                >
                  {answer}
                </button>
              ))}
            </div>
          </div>
        </div>
      );
    }

    // ========================================
    // NOT SURE
    // ========================================

    if (formData.goal === "Not Sure Yet") {
      return (
        <div>
          <h2>Let's Explore Your Options</h2>

          <p className="form-description">
            Don't worry if you're not sure. Tell us what
            interests you and we'll help you explore.
          </p>

          <div className="form-group">
            <label>What fields interest you?</label>

            <div className="options">
              {[
                "Technology",
                "Medical",
                "Business",
                "Finance",
                "Design",
                "Government",
                "Teaching",
                "Research",
              ].map((interest) => (
                <button
                  type="button"
                  key={interest}
                  className={
                    formData.interests.includes(interest)
                      ? "selected"
                      : ""
                  }
                  onClick={() => handleInterest(interest)}
                >
                  {interest}
                </button>
              ))}
            </div>
          </div>

          <div className="form-group">
            <label>What do you need help with?</label>

            <textarea
              name="careerGoal"
              value={formData.careerGoal}
              onChange={handleChange}
              placeholder="Example: I am confused about what I should study after 12th..."
            />
          </div>
        </div>
      );
    }

    return null;
  };

  // ================================
  // MAIN RETURN
  // ================================

  return (
    <div className="assessment-page">

      {/* ================================
          NAVBAR
      ================================= */}

      <Navbar />

      {/* ================================
          ASSESSMENT MAIN CONTENT
      ================================= */}

      <main className="assessment-container">

        {/* INTRO */}

        <div className="assessment-intro">

          <span>PERSONALIZED GUIDANCE</span>

          <h1>Tell Us About Yourself</h1>

          <p>
            Share a few details about your education and
            future goals so we can help you find the right path.
          </p>

        </div>

        {/* PROGRESS */}

        <div className="progress">

          <div className={step >= 1 ? "active" : ""}>
            <span>1</span>
            Basic Details
          </div>

          <div className={step >= 2 ? "active" : ""}>
            <span>2</span>
            Education
          </div>

          <div className={step >= 3 ? "active" : ""}>
            <span>3</span>
            Future Goal
          </div>

          <div className={step >= 4 ? "active" : ""}>
            <span>4</span>
            Your Preferences
          </div>

        </div>

        {/* FORM CARD */}

        <div className="assessment-card">

          {/* ================================
              STEP 1
          ================================= */}

          {step === 1 && (
            <div>

              <h2>Basic Details</h2>

              <p className="form-description">
                Let's start with some basic information.
              </p>

              <div className="form-group">

                <label>Full Name</label>

                <input
                  type="text"
                  name="name"
                  value={formData.name}
                  onChange={handleChange}
                  placeholder="Enter your name"
                />

              </div>

              <div className="form-row">

                <div className="form-group">

                  <label>Age</label>

                  <input
                    type="number"
                    name="age"
                    value={formData.age}
                    onChange={handleChange}
                    placeholder="Your age"
                  />

                </div>

                <div className="form-group">

                  <label>Location</label>

                  <input
                    type="text"
                    name="location"
                    value={formData.location}
                    onChange={handleChange}
                    placeholder="City / State"
                  />

                </div>

              </div>

            </div>
          )}

          {/* ================================
              STEP 2
          ================================= */}

          {step === 2 && (
            <div>

              <h2>Education</h2>

              <p className="form-description">
                Tell us about your current education.
              </p>

              <div className="form-group">

                <label>Current Qualification</label>

                <select
                  name="qualification"
                  value={formData.qualification}
                  onChange={handleChange}
                >

                  <option value="">
                    Select qualification
                  </option>

                  <option value="10th">
                    10th
                  </option>

                  <option value="12th">
                    12th
                  </option>

                  <option value="Diploma">
                    Diploma
                  </option>

                  <option value="Graduation">
                    Graduation
                  </option>

                  <option value="Post Graduation">
                    Post Graduation
                  </option>

                </select>

              </div>

              <div className="form-row">

                <div className="form-group">

                  <label>Stream</label>

                  <select
                    name="stream"
                    value={formData.stream}
                    onChange={handleChange}
                  >

                    <option value="">
                      Select stream
                    </option>

                    <option value="Science">
                      Science
                    </option>

                    <option value="Commerce">
                      Commerce
                    </option>

                    <option value="Arts">
                      Arts
                    </option>

                    <option value="Other">
                      Other
                    </option>

                  </select>

                </div>

                <div className="form-group">

                  <label>Marks / CGPA</label>

                  <input
                    type="text"
                    name="marks"
                    value={formData.marks}
                    onChange={handleChange}
                    placeholder="Example: 82% or 8.2 CGPA"
                  />

                </div>

              </div>

              <div className="form-group">

                <label>Passing Year</label>

                <select
                  name="passingYear"
                  value={formData.passingYear}
                  onChange={handleChange}
                >

                  <option value="">
                    Select year
                  </option>

                  <option value="2026">
                    2026
                  </option>

                  <option value="2025">
                    2025
                  </option>

                  <option value="2024">
                    2024
                  </option>

                  <option value="2023">
                    2023
                  </option>

                  <option value="2022">
                    2022
                  </option>

                </select>

              </div>

            </div>
          )}

          {/* ================================
              STEP 3
          ================================= */}

          {step === 3 && (
            <div>

              <h2>
                What Do You Want To Do Next?
              </h2>

              <p className="form-description">
                Choose the option that best describes your
                current goal.
              </p>

              <div className="form-group">

                <div className="options">

                  {[
                    "Higher Studies",
                    "Get a Job",
                    "Learn Skills",
                    "Start a Business",
                    "Not Sure Yet",
                  ].map((goal) => (

                    <button
                      type="button"
                      key={goal}
                      className={
                        formData.goal === goal
                          ? "selected"
                          : ""
                      }
                      onClick={() => handleGoal(goal)}
                    >
                      {goal}
                    </button>

                  ))}

                </div>

              </div>

            </div>
          )}

          {/* ================================
              STEP 4
          ================================= */}

          {step === 4 && renderStepFour()}

          {/* ================================
              ERROR MESSAGE
          ================================= */}

          {error && (
            <p className="assessment-error">
              {error}
            </p>
          )}

          {/* ================================
              BUTTONS
          ================================= */}

          <div className="form-buttons">

            {step > 1 && (
              <button
                className="back-button"
                onClick={previousStep}
                disabled={isSubmitting}
              >
                ← Back
              </button>
            )}

            {step < 4 ? (
              <button
                className="continue-button"
                onClick={nextStep}
                disabled={isSubmitting}
              >
                Continue →
              </button>
            ) : (
              <button
                className="continue-button"
                onClick={handleSubmit}
                disabled={isSubmitting}
              >
                {isSubmitting
                  ? "Analyzing..."
                  : "Analyze My Profile →"}
              </button>
            )}

          </div>

        </div>

        {/* ================================
            PRIVACY
        ================================= */}

        <p className="privacy-note">
          🔒 Your information is used only to personalize
          your recommendations.
        </p>

      </main>

      {/* ================================
          FOOTER
      ================================= */}

      <Footer />

    </div>
  );
}

export default Assessment;
